export const BASE_URL = "http://localhost:5000";
export const SET_USER = "SET_USER";
// ADMIN
export const SET_ADMIN = "SET_ADMIN";
export const SET_ADD_BUILDING = "SET_ADD_BUILDING";
export const SET_EDIT_BUILDING = "SET_EDIT_BUILDING";
export const SET_SEARCH_BUILDING = "SET_SEARCH_BUILDING";
export const SET_ADD_MANAGER = "SET_ADD_MANAGER";
export const SET_EDIT_MANAGER = "SET_EDIT_MANAGER";
export const SET_SEARCH_MANAGER = "SET_SEARCH_MANAGER";
// MANAGER
export const SET_MANAGER = "SET_MANAGER";
export const SET_ADD_APARTMENT = "SET_ADD_APARTMENT";
export const SET_EDIT_APARTMENT = "SET_EDIT_APARTMENT";
export const SET_SEARCH_APARTMENT = "SET_SEARCH_APARTMENT";
export const SET_ADD_TENANT = "SET_ADD_TENANT";
export const SET_SEARCH_TENANT = "SET_SEARCH_TENANT";
export const SET_EDIT_TENANT = "SET_EDIT_TENANT";
export const SET_ADD_CREW = "SET_ADD_CREW";
export const SET_EDIT_CREW = "SET_EDIT_CREW";
export const SET_SEARCH_CREW = "SET_SEARCH_CREW";
